on:
  push:
    branches:
      - main
  pull_request:

name: Linting
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: kubeval
      run: make kubeval